export const companyDiagram = {
  components: [
    {
      name: "Компонента 1",
      id: 101,
      // component_lead: id, // number
      teamId: [305, 303, 301],
      isActive: true, // boolean
      type: "mobile", // options: mobile, web, back
    },
    {
      name: "Компонента 2",
      id: 102,
      // component_lead: id, // number
      teamId: [302, 304, 313],
      isActive: true, // boolean
      type: "mobile", // options: mobile, web, back
    },
    {
      name: "Компонента 3",
      id: 103,
      // component_lead: id, // number
      teamId: [306, 314],
      isActive: true, // boolean
      type: "mobile", // options: mobile, web, back
    },
  ],

  departments: [
    {
      name: "Дизайн",
      id: 201,
      // department_lead: id, // number
      teamId: [301, 302],
    },
    {
      name: "Девелопмент",
      id: 202,
      // department_lead: id, // number
      teamId: [302, 303],
    },
    {
      name: "Анализ",
      id: 203,
      // department_lead: id, // number
      teamId: [305, 306],
    },
    {
      name: "Менеджмент",
      id: 204,
      // department_lead: id, // number
      teamId: [307, 308],
    },
    {
      name: "Маркетинг",
      id: 205,
      // department_lead: id, // number
      teamId: [309, 310],
    },
    {
      name: "HR",
      id: 206,
      // department_lead: id, // number
      teamId: [311, 312],
    },
    {
      name: "Девопсы",
      id: 207,
      // department_lead: id, // number
      teamId: [313, 314],
    },
  ],

  teams: [
    {
      name: "Команда Дизайн 1",
      id: 301,
      // team_lead: id, // number
      componentId: [101],
      // usersId: [401, 402, 403],
      // usersId: [401, 402, 403, 404],
      usersId: [401, 402, 403, 404, 405],
      // departmentId: id, // number
      performance: "", // описание
      description: "", // описание
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
    {
      name: "Команда Дизайн 2",
      id: 302,
      // team_lead: id, // number
      componentId: [102],
      usersId: [405, 408, 409],
    },
    {
      name: "Команда Девелопмент 1",
      id: 303,
      // team_lead: id, // number
      componentId: [101],
      usersId: [404, 407, 408],
    },
    {
      name: "Команда Девелопмент 2",
      id: 304,
      // team_lead: id, // number
      componentId: [102],
      usersId: [404, 407, 408],
    },
    {
      name: "Команда Анализ 1",
      id: 305,
      // team_lead: id, // number
      componentId: [101],
      usersId: [404, 407, 408],
    },
    {
      name: "Команда Анализ 2",
      id: 306,
      // team_lead: id, // number
      componentId: [103],
      usersId: [404, 407, 408],
    },
    {
      name: "Команда Менеджмент 1",
      id: 307,
      // team_lead: id, // number
      componentId: null,
      usersId: [404, 407, 408],
    },
    {
      name: "Команда Менеджмент 2",
      id: 308,
      // team_lead: id, // number
      componentId: null,
      usersId: [404, 407, 408],
    },
    {
      name: "Команда Маркетинг 1",
      id: 309,
      // team_lead: id, // number
      componentId: null,
      usersId: [404, 407, 408],
    },
    {
      name: "Команда Маркетинг 2",
      id: 310,
      // team_lead: id, // number
      componentId: null,
      usersId: [404, 407, 408],
    },
    {
      name: "Команда HR 1",
      id: 311,
      // team_lead: id, // number
      componentId: null,
      usersId: [404, 407, 408],
    },
    {
      name: "Команда HR 2",
      id: 312,
      // team_lead: id, // number
      componentId: null,
      usersId: [404, 407, 408],
    },
    {
      name: "Команда Девопсы 1",
      id: 313,
      // team_lead: id, // number
      componentId: [101],
      usersId: [404, 407, 408],
    },
    {
      name: "Команда Девопсы 2",
      id: 314,
      // team_lead: id, // number
      componentId: [102],
      usersId: [404, 407, 408],
    },
  ],
};

export const companyStructure = [
  {
    id: 401,
    first_name: "Вероника",
    last_name: "Некрасова",
    photo:
      "https://shkolafdorovka-r64.gosweb.gosuslugi.ru/netcat_files/9/167/avatar_5.png",
    position: "SEO",
    grade: "B",
    level: 1,
    componentId: 101,
    teamId: null,
    departmentId: 201,
    boss: null,
    town: "Москва",
    employment_type: "Штатные",
    timezone: "GMT",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
      email: ["eleonora_1985@example.com", "eleohjjkgnora_1985@example.com"],
      phone: ["+7 (691) 654-2862", "+7 (691) 654-8962"],
    },
  },
  {
    id: 402,
    first_name: "402",
    last_name: "Некруреукеркуеасова",
    photo:
      "https://avatars.mds.yandex.net/i?id=2f942270d036dd442f20f4d10aa7504279b0cbbb-4577690-images-thumbs&n=13",
    position: "Дев-хэд",
    grade: "A",
    level: 2,
    componentId: 101,
    teamId: null,
    departmentId: 202,
    boss: 401,
    town: "Москва",
    employment_type: "Аутсорс",
    timezone: "GMT1",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
      email: ["eleonora_1985@example.com", "eleohjjkgnora_1985@example.com"],
      phone: ["+7 (691) 654-2862", "+7 (691) 654-8962"],
    },
  },
  {
    id: 403,
    first_name: "403",
    last_name: "Некруреукеркуеасова",
    photo:
      "https://avatars.mds.yandex.net/i?id=2f942270d036dd442f20f4d10aa7504279b0cbbb-4577690-images-thumbs&n=13",
    position: "Дев-лид-1",
    grade: "B",
    level: 3,
    componentId: 102,
    teamId: 303,
    departmentId: 203,
    boss: 402,
    town: "Москва",
    employment_type: "Штатные",
    timezone: "GMT2",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
      email: ["eleonora_1985@example.com", "eleohjjkgnora_1985@example.com"],
      phone: ["+7 (691) 654-2862", "+7 (691) 654-8962"],
    },
  },
  {
    id: 404,
    first_name: "404",
    last_name: "Некруреукеркуеасова",
    photo:
      "https://avatars.mds.yandex.net/i?id=2f942270d036dd442f20f4d10aa7504279b0cbbb-4577690-images-thumbs&n=13",
    position: "Дев-лид-2",
    grade: "C",
    level: 3,
    componentId: 103,
    teamId: 304,
    departmentId: 204,
    boss: 402,
    town: "Москва",
    employment_type: "Аутсорс",
    timezone: "GMT2",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
      email: ["eleonora_1985@example.com", "eleohjjkgnora_1985@example.com"],
      phone: ["+7 (691) 654-2862", "+7 (691) 654-8962"],
    },
  },
  {
    id: 405,
    first_name: "405",
    last_name: "Некруреукеркуеасова",
    photo:
      "https://avatars.mds.yandex.net/i?id=2f942270d036dd442f20f4d10aa7504279b0cbbb-4577690-images-thumbs&n=13",
    position: "Дев-разраб-1-Тим-1",
    grade: "B",
    level: 4,
    componentId: 101,
    teamId: 303,
    departmentId: 205,
    boss: 403,
    town: "Москва",
    employment_type: "Аутсорс",
    timezone: "GMT3",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
      email: ["eleonora_1985@example.com", "eleohjjkgnora_1985@example.com"],
      phone: ["+7 (691) 654-2862", "+7 (691) 654-8962"],
    },
  },
  {
    id: 406,
    first_name: "406",
    last_name: "Некруреукеркуеасова",
    photo:
      "https://avatars.mds.yandex.net/i?id=2f942270d036dd442f20f4d10aa7504279b0cbbb-4577690-images-thumbs&n=13",
    position: "Дев-разраб-2-Тим-1",
    grade: "B",
    level: 4,
    componentId: 101,
    teamId: 303,
    departmentId: 206,
    boss: 403,
    town: "Москва",
    employment_type: "Штатные",
    timezone: "GMT3",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
      email: ["eleonora_1985@example.com", "eleohjjkgnora_1985@example.com"],
      phone: ["+7 (691) 654-2862", "+7 (691) 654-8962"],
    },
  },
  {
    id: 407,
    first_name: "407",
    last_name: "Некруреукеркуеасова",
    photo:
      "https://avatars.mds.yandex.net/i?id=2f942270d036dd442f20f4d10aa7504279b0cbbb-4577690-images-thumbs&n=13",
    position: "Дев-разраб-1-Тим-2",
    grade: "B",
    level: 4,
    componentId: 103,
    teamId: 303,
    departmentId: 207,
    boss: 404,
    town: "Москва",
    employment_type: "Аутсорс",
    timezone: "GMT3",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
      email: ["eleonora_1985@example.com", "eleohjjkgnora_1985@example.com"],
      phone: ["+7 (691) 654-2862", "+7 (691) 654-8962"],
    },
  },
  {
    id: 408,
    first_name: "408",
    last_name: "Некруреукеркуеасова",
    photo:
      "https://avatars.mds.yandex.net/i?id=2f942270d036dd442f20f4d10aa7504279b0cbbb-4577690-images-thumbs&n=13",
    position: "Дев-разраб-2-Тим-2",
    grade: "B",
    level: 4,
    componentId: 102,
    teamId: 303,
    departmentId: 202,
    boss: 404,
    town: "Москва",
    employment_type: "Штатные",
    timezone: "GMT5",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
      email: ["eleonora_1985@example.com", "eleohjjkgnora_1985@example.com"],
      phone: ["+7 (691) 654-2862", "+7 (691) 654-8962"],
    },
  },
];

export const userStructure = {
  id: 2,
  first_name: "Елена",
  last_name: "Тестовая",
  photo:
    "https://hackathonproject.sytes.net/media/user_photos/01._Ivan_Petrov.jpg",
  position: "Разработчик",
  level: 4,
  grade: "Junior+",
  bossId: 1,
  teamId: 301,
  componentId: 101,
  employment_type: "Аутсорс",
  timezone: "Poland",
  town: "Москва",
  foreign_languages: ["Японский", "Английский"],
  programs: ["Python", "C++"],
  skills: ["Мобильная разработка", "Бекенд-разработка"],
  contacts: {
    links: [
      "https://telegram.org",
      "https://myteam.mail.ru/webim",
      "https://www.atlassian.com/ru/software/jira",
    ],
    emails: ["test@test.ru", "test2@test.ru"],
    phones: ["1111111111", "22222222222"],
  },
};

/////////////////////////////////////////// from back
export const users = [
  {
    id: 425,
    first_name: "Екатерина",
    last_name: "Бурнаева",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/39._%D0%95%D0%BA%D0%B0%D1%82%D0%B5%D1%80%D0%B8%D0%BD%D0%B0_%D0%91%D1%83%D1%80%D0%BD%D0%B0%D0%B5%D0%B2%D0%B0.jpg",
    position: "Девопс",
    level: 4,
    grade: "Team Lead",
    bossId: 431,
    componentId: 103,
    teamId: 313,
    departmentId: 226,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 411,
    first_name: "Дмитрий",
    last_name: "Сергеев",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/08._%D0%94%D0%BC%D0%B8%D1%82%D1%80%D0%B8%D0%B9_%D0%A1%D0%B5%D1%80%D0%B3%D0%B5%D0%B5%D0%B2.jpg",
    position: "Фронтенд-разработчик",
    level: 4,
    grade: "Middle",
    bossId: 410,
    componentId: 104,
    teamId: 306,
    departmentId: 203,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 455,
    first_name: "Елена",
    last_name: "Осипова",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/15._%D0%95%D0%BB%D0%B5%D0%BD%D0%B0_%D0%9E%D1%81%D0%B8%D0%BF%D0%BE%D0%B2%D0%B0.jpg",
    position: "Руководитель команды Дизайн 2",
    level: 3,
    grade: "Team Lead",
    bossId: 440,
    teamId: 303,
    departmentId: 202,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 470,
    first_name: "Сергей",
    last_name: "Васильев",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/20._%D0%A1%D0%B5%D1%80%D0%B3%D0%B5%D0%B9_%D0%92%D0%B0%D1%81%D0%B8%D0%BB%D1%8C%D0%B5%D0%B2.jpg",
    position: "Руководитель команды Анализ 2",
    level: 3,
    grade: "Team Lead",
    bossId: 417,
    componentId: 104,
    teamId: 308,
    departmentId: 212,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 413,
    first_name: "Семен",
    last_name: "Кузнецов",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/11._%D0%A1%D0%B5%D0%BC%D0%B5%D0%BD_%D0%9A%D1%83%D0%B7%D0%BD%D0%B5%D1%86%D0%BE%D0%B2.jpg",
    position: "Руководитель команды Дизайн 1",
    level: 3,
    grade: "Team Lead",
    bossId: 440,
    componentId: 102,
    teamId: 301,
    departmentId: 202,
    employment_type: "Полная занятость",
    town: "Киров",
    timezone: "Europe/Kirov",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 416,
    first_name: "Никита",
    last_name: "Тарасов",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/17._%D0%9D%D0%B8%D0%BA%D0%B8%D1%82%D0%B0_%D0%A2%D0%B0%D1%80%D0%B0%D1%81%D0%BE%D0%B2.jpg",
    position: "Руководитель команды Анализ 1",
    level: 3,
    grade: "Team Lead",
    bossId: 417,
    componentId: 102,
    teamId: 307,
    departmentId: 212,
    employment_type: "Полная занятость",
    town: "Калининград",
    timezone: "Europe/Kaliningrad",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 431,
    first_name: "Светлана",
    last_name: "Евдокимова",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/40._%D0%A1%D0%B2%D0%B5%D1%82%D0%BB%D0%B0%D0%BD%D0%B0_%D0%95%D0%B2%D0%B4%D0%BE%D0%BA%D0%B8%D0%BC%D0%BE%D0%B2%D0%B0.jpg",
    position: "Руководитель команды Девопс 2",
    level: 3,
    grade: "Team Lead",
    bossId: 423,
    componentId: 103,
    teamId: 313,
    departmentId: 226,
    employment_type: "Полная занятость",
    town: "Самара",
    timezone: "Europe/Samara",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 424,
    first_name: "Семен",
    last_name: "Плавников",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/37._%D0%A1%D0%B5%D0%BC%D0%B5%D0%BD_%D0%9F%D0%BB%D0%B0%D0%B2%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2.jpg",
    position: "Руководитель команды Девопсы 1",
    level: 3,
    grade: "Team Lead",
    bossId: 423,
    componentId: 102,
    teamId: 312,
    departmentId: 226,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 418,
    first_name: "Александр",
    last_name: "Гусев",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/30._%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%93%D1%83%D1%81%D0%B5%D0%B2.jpg",
    position: "Руководитель группы Менеджмент 1",
    level: 3,
    grade: "Team Lead",
    bossId: 473,
    teamId: 309,
    departmentId: 215,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 405,
    first_name: "Сергей",
    last_name: "Киселев",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/05._%D0%A1%D0%B5%D1%80%D0%B3%D0%B5%D0%B9_%D0%9A%D0%B8%D1%81%D0%B5%D0%BB%D0%B5%D0%B2.jpg",
    position: "Руководитель команды Девелопмент 2",
    level: 3,
    grade: "Team Lead",
    bossId: 406,
    componentId: 103,
    teamId: 305,
    departmentId: 203,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 410,
    first_name: "Георгий",
    last_name: "Максимов",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/09._%D0%93%D0%B5%D0%BE%D1%80%D0%B3%D0%B8%D0%B9_%D0%9C%D0%B0%D0%BA%D1%81%D0%B8%D0%BC%D0%BE%D0%B2.jpg",
    position: "Руководитель команды Девелопмент 3",
    level: 3,
    grade: "Team Lead",
    bossId: 406,
    componentId: 104,
    teamId: 306,
    departmentId: 203,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 402,
    first_name: "Иван",
    last_name: "Петров",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/01._Ivan_Petrov.jpg",
    position: "Руководитель команды Девелопмент 1",
    level: 3,
    grade: "Team Lead",
    bossId: 406,
    componentId: 102,
    teamId: 304,
    departmentId: 203,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 414,
    first_name: "Сергей",
    last_name: "Тихомиров",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/12._%D0%A1%D0%B5%D1%80%D0%B3%D0%B5%D0%B9_%D0%A2%D0%B8%D1%85%D0%BE%D0%BC%D0%B8%D1%80%D0%BE%D0%B2.jpg",
    position: "Веб-дизайнер",
    level: 4,
    grade: "Middle",
    bossId: 413,
    componentId: 102,
    teamId: 301,
    departmentId: 202,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 412,
    first_name: "Павел",
    last_name: "Иванов",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/10._%D0%9F%D0%B0%D0%B2%D0%B5%D0%BB_%D0%98%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2.jpg",
    position: "Бекенд-разработчик",
    level: 4,
    grade: "Junior",
    bossId: 410,
    componentId: 104,
    teamId: 306,
    departmentId: 203,
    employment_type: "Полная занятость",
    town: "Самара",
    timezone: "Europe/Samara",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 444,
    first_name: "Ли",
    last_name: "Мин",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/45._%D0%9B%D0%B8_%D0%9C%D0%B8%D0%BD.jpg",
    position: "Генеральный директор",
    level: 1,
    grade: "Senior",
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 482,
    first_name: "Анатолий",
    last_name: "Власов",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/32._%D0%90%D0%BD%D0%B0%D1%82%D0%BE%D0%BB%D0%B8%D0%B9_%D0%92%D0%BB%D0%B0%D1%81%D0%BE%D0%B2.jpg",
    position: "Руководитель департамента маркетинга",
    level: 2,
    grade: "Senior",
    bossId: 444,
    departmentId: 220,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 433,
    first_name: "Ким",
    last_name: "Лунг",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/46._%D0%9A%D0%B8%D0%BC_%D0%9B%D1%83%D0%BD%D0%B3.jpg",
    position: "Руководитель команды HR 1",
    level: 3,
    grade: "Team Lead",
    bossId: 422,
    teamId: 311,
    departmentId: 205,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 473,
    first_name: "Валерия",
    last_name: "Захарова",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/23._%D0%92%D0%B0%D0%BB%D0%B5%D1%80%D0%B8%D1%8F_%D0%97%D0%B0%D1%85%D0%B0%D1%80%D0%BE%D0%B2%D0%B0.jpg",
    position: "Руководитель департамента менеджмента",
    level: 2,
    grade: "Senior",
    bossId: 444,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 440,
    first_name: "Александр",
    last_name: "Никитин",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/14._%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%9D%D0%B8%D0%BA%D0%B8%D1%82%D0%B8%D0%BD.jpg",
    position: "Руководитель департамента дизайна",
    level: 2,
    grade: "Senior",
    bossId: 444,
    departmentId: 202,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 427,
    first_name: "Лина",
    last_name: "Морозова",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/43._%D0%9B%D0%B8%D0%BD%D0%B0_%D0%9C%D0%BE%D1%80%D0%BE%D0%B7%D0%BE%D0%B2%D0%B0.jpg",
    position: "Руководитель проекта IT-компонент 3",
    level: 2,
    grade: "Senior",
    bossId: 444,
    employment_type: "Полная занятость",
    town: "Киров",
    timezone: "Europe/Kirov",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 426,
    first_name: "Петр",
    last_name: "Горонов",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/42._%D0%9F%D0%B5%D1%82%D1%80_%D0%93%D0%BE%D1%80%D0%BE%D0%BD%D0%BE%D0%B2.jpg",
    position: "Руководитель проекта IT-компонент 2",
    level: 2,
    grade: "Senior",
    bossId: 444,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 423,
    first_name: "Раджеш",
    last_name: "Кутраппали",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/34._%D0%A0%D0%B0%D0%B4%D0%B6%D0%B5%D1%88_%D0%9A%D1%83%D1%82%D1%80%D0%B0%D0%BF%D0%BF%D0%B0%D0%BB%D0%B8.jpg",
    position: "Руководитель департамента девопс",
    level: 2,
    grade: "Senior",
    bossId: 444,
    departmentId: 226,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 422,
    first_name: "Екатерина",
    last_name: "Симонова",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/34._%D0%95%D0%BA%D0%B0%D1%82%D0%B5%D1%80%D0%B8%D0%BD%D0%B0_%D0%A1%D0%B8%D0%BC%D0%BE%D0%BD%D0%BE%D0%B2%D0%B0.jpg",
    position: "Руководитель департамента HR",
    level: 2,
    grade: "Senior",
    bossId: 444,
    departmentId: 205,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 417,
    first_name: "Владимир",
    last_name: "Морозов",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/19._%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80_%D0%9C%D0%BE%D1%80%D0%BE%D0%B7%D0%BE%D0%B2_DcmeNo7.jpg",
    position: "Руководитель департамента анализа",
    level: 2,
    grade: "Senior",
    bossId: 444,
    departmentId: 212,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 409,
    first_name: "Максим",
    last_name: "Некрасов",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/07._%D0%9C%D0%B0%D0%BA%D1%81%D0%B8%D0%BC_%D0%9D%D0%B5%D0%BA%D1%80%D0%B0%D1%81%D0%BE%D0%B2.jpg",
    position: "Фронтенд-разработчик",
    level: 4,
    grade: "Middle",
    bossId: 405,
    componentId: 103,
    teamId: 305,
    departmentId: 203,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 404,
    first_name: "Сергей",
    last_name: "Петров",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/03._%D0%A1%D0%B5%D1%80%D0%B3%D0%B5%D0%B9_%D0%9F%D0%B5%D1%82%D1%80%D0%BE%D0%B2.jpg",
    position: "Бекенд-разработчик",
    level: 4,
    grade: "Junior",
    bossId: 402,
    componentId: 102,
    teamId: 304,
    departmentId: 203,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 443,
    first_name: "Георгий",
    last_name: "Гигашвилли",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/48._%D0%93%D0%B5%D0%BE%D1%80%D0%B3%D0%B8%D0%B9_%D0%93%D0%B8%D0%B3%D0%B0%D1%88%D0%B2%D0%B8%D0%BB%D0%BB%D0%B8.jpg",
    position: "Девопс",
    level: 4,
    grade: "Middle",
    bossId: 424,
    componentId: 102,
    teamId: 312,
    departmentId: 226,
    employment_type: "Полная занятость",
    town: "Саратов",
    timezone: "Europe/Saratov",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 434,
    first_name: "Зинаида",
    last_name: "Полкова",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/47._%D0%97%D0%B8%D0%BD%D0%B0%D0%B8%D0%B4%D0%B0_%D0%9F%D0%BE%D0%BB%D0%BA%D0%BE%D0%B2%D0%B0.jpg",
    position: "HR",
    level: 4,
    grade: "Middle",
    bossId: 433,
    teamId: 311,
    departmentId: 205,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 415,
    first_name: "Анна",
    last_name: "Матвеева",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/16._%D0%90%D0%BD%D0%BD%D0%B0_%D0%9C%D0%B0%D1%82%D0%B2%D0%B5%D0%B5%D0%B2%D0%B0.jpg",
    position: "Веб-дизайнер",
    level: 4,
    grade: "Middle",
    bossId: 455,
    teamId: 303,
    departmentId: 202,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 437,
    first_name: "Алексей",
    last_name: "Соколов",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/18._%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B9_%D0%A1%D0%BE%D0%BA%D0%BE%D0%BB%D0%BE%D0%B2.jpg",
    position: "Системный аналитик",
    level: 4,
    grade: "Junior",
    bossId: 416,
    componentId: 102,
    teamId: 307,
    departmentId: 212,
    employment_type: "Фриланс",
    town: "Калилинград",
    timezone: "Europe/Kaliningrad",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 435,
    first_name: "Ирина",
    last_name: "Торшина",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/50._%D0%98%D1%80%D0%B8%D0%BD%D0%B0_%D0%A2%D0%BE%D1%80%D1%88%D0%B8%D0%BD%D0%B0.jpg",
    position: "Дизайнер",
    level: 4,
    grade: "Junior",
    bossId: 413,
    componentId: 102,
    teamId: 301,
    departmentId: 202,
    employment_type: "Фриланс",
    town: "Киров",
    timezone: "Europe/Kirov",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 449,
    first_name: "Арина",
    last_name: "Васильева",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/53._%D0%90%D1%80%D0%B8%D0%BD%D0%B0_%D0%92%D0%B0%D1%81%D0%B8%D0%BB%D1%8C%D0%B5%D0%B2%D0%B0.jpg",
    position: "Системный аналитик",
    level: 4,
    grade: "Middle",
    bossId: 470,
    componentId: 104,
    teamId: 308,
    departmentId: 212,
    employment_type: "Фриланс",
    town: "Киров",
    timezone: "Europe/Kirov",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 421,
    first_name: "Алексей",
    last_name: "Макаров",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/34._%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B9_%D0%9C%D0%B0%D0%BA%D0%B0%D1%80%D0%BE%D0%B2.jpg",
    position: "Маркетолог",
    level: 4,
    grade: "Middle",
    bossId: 420,
    teamId: 310,
    departmentId: 220,
    employment_type: "Фриланс",
    town: "Мадрид",
    timezone: "Europe/Madrid",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 420,
    first_name: "Петр",
    last_name: "Яковлев",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/33._%D0%9F%D0%B5%D1%82%D1%80_%D0%AF%D0%BA%D0%BE%D0%B2%D0%BB%D0%B5%D0%B2.jpg",
    position: "Руководитель команды Маркетинг 1",
    level: 3,
    grade: "Team Lead",
    bossId: 482,
    teamId: 310,
    departmentId: 220,
    employment_type: "Полная занятость",
    town: "Волгоград",
    timezone: "Europe/Volgograd",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 419,
    first_name: "Николай",
    last_name: "Поляков",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/30._%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9_%D0%9F%D0%BE%D0%BB%D1%8F%D0%BA%D0%BE%D0%B2.jpg",
    position: "Менеджер",
    level: 4,
    grade: "Middle",
    bossId: 418,
    teamId: 309,
    departmentId: 215,
    employment_type: "Полная занятость",
    town: "Стамбул",
    timezone: "Europe/Istanbul",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 502,
    first_name: "Артем",
    last_name: "Кириллов",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/38._%D0%90%D1%80%D1%82%D0%B5%D0%BC_%D0%9A%D0%B8%D1%80%D0%B8%D0%BB%D0%BB%D0%BE%D0%B2.jpg",
    position: "Девопс",
    level: 4,
    grade: "Junior",
    bossId: 424,
    componentId: 102,
    teamId: 312,
    departmentId: 226,
    employment_type: "Фриланс",
    town: "Стамбул",
    timezone: "Europe/Istanbul",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 442,
    first_name: "Лу",
    last_name: "Ван",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/52._%D0%9B%D1%83_%D0%92%D0%B0%D0%BD.jpg",
    position: "Системный аналитик",
    level: 4,
    grade: "Junior",
    bossId: 416,
    componentId: 102,
    teamId: 307,
    departmentId: 212,
    employment_type: "Фриланс",
    town: "Амстердам",
    timezone: "Europe/Amsterdam",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 408,
    first_name: "Николай",
    last_name: "Сергеев",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/06._%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9_%D0%A1%D0%B5%D1%80%D0%B3%D0%B5%D0%B5%D0%B2.jpg",
    position: "Бекенд-разработчик",
    level: 4,
    grade: "Junior",
    bossId: 405,
    componentId: 103,
    teamId: 305,
    departmentId: 203,
    employment_type: "Фриланс",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 438,
    first_name: "Николай",
    last_name: "Орлов",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/21._%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9_%D0%9E%D1%80%D0%BB%D0%BE%D0%B2.jpg",
    position: "Системный аналитик",
    level: 4,
    grade: "Junior",
    bossId: 470,
    componentId: 104,
    teamId: 308,
    departmentId: 212,
    employment_type: "Фриланс",
    town: "Волгоград",
    timezone: "Europe/Volgograd",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 429,
    first_name: "Елена",
    last_name: "Плотникова",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/41._%D0%95%D0%BB%D0%B5%D0%BD%D0%B0_%D0%9F%D0%BB%D0%BE%D1%82%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2%D0%B0.jpg",
    position: "Девопс",
    level: 4,
    grade: "Middle",
    bossId: 431,
    componentId: 103,
    teamId: 313,
    departmentId: 226,
    employment_type: "Фриланс",
    town: "Будапешт",
    timezone: "Europe/Budapest",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 403,
    first_name: "Елена",
    last_name: "Кольцова",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/02._%D0%95%D0%BB%D0%B5%D0%BD%D0%B0_%D0%9A%D0%BE%D0%BB%D1%8C%D1%86%D0%BE%D0%B2%D0%B0.jpg",
    position: "Фронтенд-разработчик",
    level: 4,
    grade: "Middle",
    bossId: 402,
    componentId: 102,
    teamId: 304,
    departmentId: 203,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 457,
    first_name: "Елена",
    last_name: "Плющева",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/54._%D0%95%D0%BB%D0%B5%D0%BD%D0%B0_%D0%9F%D0%BB%D1%8E%D1%89%D0%B5%D0%B2%D0%B0.jpg",
    position: "Системный аналитик",
    level: 4,
    grade: "Junior",
    bossId: 470,
    componentId: 104,
    teamId: 308,
    departmentId: 212,
    employment_type: "Полная занятость",
    town: "Калининград",
    timezone: "Europe/Kaliningrad",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 464,
    first_name: "Никита",
    last_name: "Морозов",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/%D0%9D%D0%B8%D0%BA%D0%B8%D1%82%D0%B0_%D0%9C%D0%BE%D1%80%D0%BE%D0%B7%D0%BE%D0%B2.jpg",
    position: "Руководитель проекта IT-компонент 1",
    level: 2,
    grade: "Senior",
    bossId: 444,
    departmentId: 212,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 406,
    first_name: "Даниил",
    last_name: "Тихомиров",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/04._%D0%94%D0%B0%D0%BD%D0%B8%D0%B8%D0%BB_%D0%A2%D0%B8%D1%85%D0%BE%D0%BC%D0%B8%D1%80%D0%BE%D0%B2.jpg",
    position: "Руководитель департамента девелопмента",
    level: 2,
    grade: "Senior",
    bossId: 444,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/London",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 452,
    first_name: "Петр",
    last_name: "Янг",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/55._%D0%9F%D0%B5%D1%82%D1%80_%D0%AF%D0%BD%D0%B3.jpg",
    position: "Бекенд-разработчик",
    level: 4,
    grade: "Junior",
    bossId: 410,
    componentId: 104,
    teamId: 306,
    departmentId: 203,
    employment_type: "Полная занятость",
    town: "Таллин",
    timezone: "Europe/Tallinn",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 432,
    first_name: "Петр",
    last_name: "Никитин",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/49._%D0%9F%D0%B5%D1%82%D1%80_%D0%9D%D0%B8%D0%BA%D0%B8%D1%82%D0%B8%D0%BD.jpg",
    position: "Девопс",
    level: 4,
    grade: "Junior",
    bossId: 424,
    componentId: 102,
    teamId: 312,
    departmentId: 226,
    employment_type: "Полная занятость",
    town: "Варшава",
    timezone: "Europe/Warsaw",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 459,
    first_name: "Чэнь",
    last_name: "Лин",
    photo:
      "http://hackathonproject.sytes.net/media/user_photos/56._%D0%A7%D1%8D%D0%BD%D1%8C_%D0%9B%D0%B8%D0%BD.jpg",
    position: "Фронтенд-разработчик",
    level: 4,
    grade: "Junior",
    bossId: 410,
    componentId: 104,
    teamId: 306,
    departmentId: 203,
    employment_type: "Фриланс",
    town: "Лондон",
    timezone: "Europe/London",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
];

////////////////////////////////////////////////////
export const projects = [
  {
    components: [
      {
        id: 103,
        resources: [
          {
            id: 5,
            cost: 37000,
            progress: 35,
            teamId: 305,
          },
          {
            id: 6,
            cost: 43000,
            progress: 15,
            teamId: 313,
          },
        ],
        name: "Комонента 2",
        description: "",
        isActive: true,
        type: "web",
        status: "active",
        component_leadId: 426,
        teams: [305, 313],
      },
      {
        id: 104,
        resources: [
          {
            id: 7,
            cost: 37000,
            progress: 15,
            teamId: 307,
          },
          {
            id: 8,
            cost: 37000,
            progress: 45,
            teamId: 306,
          },
        ],
        name: "Комонента 3",
        description: "",
        isActive: true,
        type: "web",
        status: "active",
        component_leadId: 427,
        teams: [307, 306],
      },
      {
        id: 102,
        resources: [
          {
            id: 1,
            cost: 15000,
            progress: 25,
            teamId: 304,
          },
          {
            id: 2,
            cost: 35000,
            progress: 17,
            teamId: 307,
          },
          {
            id: 3,
            cost: 12000,
            progress: 37,
            teamId: 307,
          },
          {
            id: 4,
            cost: 16000,
            progress: 35,
            teamId: 312,
          },
        ],
        name: "Комонента 1",
        description: "",
        isActive: true,
        type: "web",
        status: "active",
        component_leadId: 464,
        teams: [307, 304, 301, 312],
      },
    ],
    departments: [
      {
        id: 203,
        department_leadId: 406,
        teamsId: [305, 304, 306],
        name: "Девелопмент",
      },
      {
        id: 202,
        department_leadId: 440,
        teamsId: [303, 301],
        name: "Дизайн",
      },
      {
        id: 215,
        department_leadId: 473,
        teamsId: [310],
        name: "Менеджмент",
      },
      {
        id: 212,
        department_leadId: 417,
        teamsId: [307, 308],
        name: "Анализ",
      },
      {
        id: 220,
        department_leadId: 482,
        teamsId: [310],
        name: "Маркетинг",
      },
      {
        id: 205,
        department_leadId: 422,
        teamsId: [311],
        name: "HR",
      },
      {
        id: 226,
        department_leadId: 423,
        teamsId: [313, 312],
        name: "Девопсы",
      },
    ],
    teams: [
      {
        id: 305,
        name: "Команда Девелопмент 2",
        team_type: "STAFF",
        performance: "Опытная слаженная команда разработчиков.",
        description:
          "Команда имеет обширный опыт решения сложных технических задач.",
        team_leadId: 405,
        componentIds: 104,
        departmentId: 203,
        usersId: [405, 409, 408],
      },
      {
        id: 313,
        name: "Команда Девопсы 2",
        team_type: "STAFF",
        performance: "Опытная слаженная команда разработчиков.",
        description:
          "Команда имеет обширный опыт решения сложных технических задач.",
        team_leadId: null,
        componentIds: null,
        departmentId: 226,
        usersId: [431, 429],
      },
      {
        id: 307,
        name: "Команда Анализ 1",
        team_type: "STAFF",
        performance: "Опытная слаженная команда разработчиков.",
        description:
          "Команда имеет обширный опыт решения сложных технических задач.",
        team_leadId: 416,
        componentIds: 102,
        departmentId: 212,
        usersId: [416, 437],
      },
      {
        id: 303,
        name: "Команда Дизайн 2",
        team_type: "STAFF",
        performance: "Опытная слаженная команда разработчиков.",
        description:
          "Команда имеет обширный опыт решения сложных технических задач.",
        team_leadId: 455,
        componentIds: null,
        departmentId: 202,
        usersId: [455, 415],
      },
      {
        id: 304,
        name: "Команда Девелопмент 1",
        team_type: "STAFF",
        performance: "Опытная слаженная команда разработчиков.",
        description:
          "Команда имеет обширный опыт решения сложных технических задач.",
        team_leadId: 402,
        componentIds: 102,
        departmentId: 203,
        usersId: [402, 404, 403],
      },
      {
        id: 309,
        name: "Команда Менеджмент 1",
        team_type: "OUTSOURCE",
        performance: "Опытная слаженная команда разработчиков.",
        description:
          "Команда имеет обширный опыт решения сложных технических задач.",
        team_leadId: 418,
        componentIds: null,
        departmentId: 215,
        usersId: [418, 419],
      },
      {
        id: 311,
        name: "Команда HR 1",
        team_type: "STAFF",
        performance: "Опытная слаженная команда разработчиков.",
        description:
          "Команда имеет обширный опыт решения сложных технических задач.",
        team_leadId: 433,
        componentIds: null,
        departmentId: 205,
        usersId: [433, 434],
      },
      {
        id: 301,
        name: "Команда Дизайн 1",
        team_type: "STAFF",
        performance: "Опытная слаженная команда разработчиков.",
        description:
          "Команда имеет обширный опыт решения сложных технических задач.",
        team_leadId: 413,
        componentIds: 102,
        departmentId: 202,
        usersId: [413, 414, 435],
      },
      {
        id: 308,
        name: "Команда Анализ 2",
        team_type: "STAFF",
        performance: "Опытная слаженная команда разработчиков.",
        description:
          "Команда имеет обширный опыт решения сложных технических задач.",
        team_leadId: 470,
        componentIds: 104,
        departmentId: 212,
        usersId: [470, 449, 438, 457],
      },
      {
        id: 312,
        name: "Команда Девопсы 1",
        team_type: "OUTSOURCE",
        performance: "Опытная слаженная команда разработчиков.",
        description:
          "Команда имеет обширный опыт решения сложных технических задач.",
        team_leadId: 424,
        componentIds: 102,
        departmentId: 226,
        usersId: [424, 443, 502, 432],
      },
      {
        id: 306,
        name: "Команда Девелопмент 3",
        team_type: "OUTSOURCE",
        performance: "Опытная слаженная команда разработчиков.",
        description:
          "Команда имеет обширный опыт решения сложных технических задач.",
        team_leadId: 410,
        componentIds: 104,
        departmentId: 203,
        usersId: [411, 410, 412, 452, 459],
      },
      {
        id: 310,
        name: "Команда Маркетинг 1",
        team_type: "OUTSOURCE",
        performance: "Опытная слаженная команда разработчиков.",
        description:
          "Команда имеет обширный опыт решения сложных технических задач.",
        team_leadId: 420,
        componentIds: null,
        departmentId: 220,
        usersId: [421, 420],
      },
    ],
  },
];

export const user = {
  id: 402,
  first_name: "Иван",
  last_name: "Петров",
  photo:
    "http://hackathonproject.sytes.net/media/user_photos/01._Ivan_Petrov.jpg",
  position: "Руководитель команды Девелопмент 1",
  level: 3,
  grade: "Team Lead",
  bossId: 406,
  teamId: 304,
  componentId: 102,
  departmentId: 203,
  employment_type: "Полная занятость",
  timezone: "Europe/Moscow",
  town: "Москва",
  foreign_languages: ["Английский"],
  programs: ["Python"],
  skills: ["Бекенд-разработка"],
  contacts: {
    links: [
      "https://telegram.org",
      "https://myteam.mail.ru/webim",
      "https://www.atlassian.com/ru/software/jira",
    ],
    emails: ["copr@mail.com", "personal@mail.com"],
    phones: ["+7(923)4567890", "+7(942)4646484"],
  },
};
