export const users = [
  {
    id: 425,
    first_name: "Екатерина",
    last_name: "Бурнаева",
    photo:
      "https://avatars.mds.yandex.net/i?id=7738b95c0b33c2cc23f3472b90ff176c_l-12569562-images-thumbs&n=13",
    position: "Девопс",
    level: 4,
    grade: "Team Lead",
    bossId: 431,
    componentId: 103,
    teamId: 313,
    departmentId: 226,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 411,
    first_name: "Дмитрий",
    last_name: "Сергеев",
    photo:
      "https://avatars.mds.yandex.net/i?id=6af834f2f930bf95babac5e69dbca0f8808125c4-12216120-images-thumbs&n=13",
    position: "Фронтенд-разработчик",
    level: 4,
    grade: "Middle",
    bossId: 410,
    componentId: 104,
    teamId: 306,
    departmentId: 203,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 455,
    first_name: "Елена",
    last_name: "Осипова",
    photo:
      "https://avatars.mds.yandex.net/i?id=3fecc26348b58700a67a03b54f9a9d7a54c7351d-12402586-images-thumbs&n=13",
    position: "Руководитель команды Дизайн 2",
    level: 3,
    grade: "Team Lead",
    bossId: 440,
    teamId: 303,
    departmentId: 202,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 470,
    first_name: "Сергей",
    last_name: "Васильев",
    photo:
      "https://avatars.mds.yandex.net/i?id=b56e299af2eab72c55d3743d0dce7aed32ebf9ed-13273717-images-thumbs&n=13",
    position: "Руководитель команды Анализ 2",
    level: 3,
    grade: "Team Lead",
    bossId: 417,
    componentId: 104,
    teamId: 308,
    departmentId: 212,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 413,
    first_name: "Семен",
    last_name: "Кузнецов",
    photo:
      "https://avatars.mds.yandex.net/i?id=532b1fc78baf48a8cea7188a5c7436bd3f2dac52-4577278-images-thumbs&n=13",
    position: "Руководитель команды Дизайн 1",
    level: 3,
    grade: "Team Lead",
    bossId: 440,
    componentId: 102,
    teamId: 301,
    departmentId: 202,
    employment_type: "Полная занятость",
    town: "Киров",
    timezone: "Europe/Kirov",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 416,
    first_name: "Никита",
    last_name: "Тарасов",
    photo:
      "https://avatars.mds.yandex.net/i?id=9ee2ffcaa42f10a56f300ca9f9992c89b054889a-10928869-images-thumbs&n=13",
    position: "Руководитель команды Анализ 1",
    level: 3,
    grade: "Team Lead",
    bossId: 417,
    componentId: 102,
    teamId: 307,
    departmentId: 212,
    employment_type: "Полная занятость",
    town: "Калининград",
    timezone: "Europe/Kaliningrad",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 431,
    first_name: "Светлана",
    last_name: "Евдокимова",
    photo:
      "https://avatars.mds.yandex.net/i?id=1cb6111179646a5942d89a91006c013c6fce2954-4570212-images-thumbs&n=13",
    position: "Руководитель команды Девопс 2",
    level: 3,
    grade: "Team Lead",
    bossId: 423,
    componentId: 103,
    teamId: 313,
    departmentId: 226,
    employment_type: "Полная занятость",
    town: "Самара",
    timezone: "Europe/Samara",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 424,
    first_name: "Семен",
    last_name: "Плавников",
    photo:
      "https://avatars.mds.yandex.net/i?id=66497615b127353ea476b033d98d8ffedec5314a-11492249-images-thumbs&n=13",
    position: "Руководитель команды Девопсы 1",
    level: 3,
    grade: "Team Lead",
    bossId: 423,
    componentId: 102,
    teamId: 312,
    departmentId: 226,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 418,
    first_name: "Александр",
    last_name: "Гусев",
    photo:
      "https://avatars.mds.yandex.net/i?id=5e987d0b3538fe1eb7af4b80eb67674698650a7e191532d8-11518590-images-thumbs&n=13",
    position: "Руководитель группы Менеджмент 1",
    level: 3,
    grade: "Team Lead",
    bossId: 473,
    teamId: 309,
    departmentId: 215,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 405,
    first_name: "Сергей",
    last_name: "Киселев",
    photo:
      "https://avatars.mds.yandex.net/i?id=82218149f878ace735a9a27718aa97e274c893cb-8181844-images-thumbs&n=13",
    position: "Руководитель команды Девелопмент 2",
    level: 3,
    grade: "Team Lead",
    bossId: 406,
    componentId: 103,
    teamId: 305,
    departmentId: 203,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 410,
    first_name: "Георгий",
    last_name: "Максимов",
    photo:
      "https://avatars.mds.yandex.net/i?id=4ad350254c2c4ede9aa986b7da1ee80464f933ae-9152550-images-thumbs&n=13",
    position: "Руководитель команды Девелопмент 3",
    level: 3,
    grade: "Team Lead",
    bossId: 406,
    componentId: 104,
    teamId: 306,
    departmentId: 203,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 402,
    first_name: "Иван",
    last_name: "Петров",
    photo:
      "https://avatars.mds.yandex.net/i?id=bc067cc5445ed0c2b7ae99e6f2c3e50454a371d5-12932370-images-thumbs&n=13",
    position: "Руководитель команды Девелопмент 1",
    level: 3,
    grade: "Team Lead",
    bossId: 406,
    componentId: 102,
    teamId: 304,
    departmentId: 203,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 414,
    first_name: "Сергей",
    last_name: "Тихомиров",
    photo:
      "https://avatars.mds.yandex.net/i?id=546f104d4c39a69570208855c10d48158dd70d4202bd8d4e-10255460-images-thumbs&n=13",
    position: "Веб-дизайнер",
    level: 4,
    grade: "Middle",
    bossId: 413,
    componentId: 102,
    teamId: 301,
    departmentId: 202,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 412,
    first_name: "Павел",
    last_name: "Иванов",
    photo:
      "https://avatars.mds.yandex.net/i?id=2fe183ccb0d3ab2fcf9b3503f125fdafdd02ece5-10986596-images-thumbs&n=13",
    position: "Бекенд-разработчик",
    level: 4,
    grade: "Junior",
    bossId: 410,
    componentId: 104,
    teamId: 306,
    departmentId: 203,
    employment_type: "Полная занятость",
    town: "Самара",
    timezone: "Europe/Samara",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 444,
    first_name: "Ли",
    last_name: "Мин",
    photo:
      "https://avatars.mds.yandex.net/i?id=b1e04501b776ac0559f11dc85028a464d517b60a-9065664-images-thumbs&n=13",
    position: "Генеральный директор",
    level: 1,
    grade: "Senior",
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 482,
    first_name: "Анатолий",
    last_name: "Власов",
    photo:
      "https://avatars.mds.yandex.net/i?id=7c2379765c3a7e26a425ad510e4210602e24def3-10787799-images-thumbs&n=13",
    position: "Руководитель департамента маркетинга",
    level: 2,
    grade: "Senior",
    bossId: 444,
    departmentId: 220,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 433,
    first_name: "Ким",
    last_name: "Лунг",
    photo:
      "https://avatars.mds.yandex.net/i?id=c4f1227d833c32729e531904f106151732da344d-4547278-images-thumbs&n=13",
    position: "Руководитель команды HR 1",
    level: 3,
    grade: "Team Lead",
    bossId: 422,
    teamId: 311,
    departmentId: 205,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 473,
    first_name: "Валерия",
    last_name: "Захарова",
    photo:
      "https://avatars.mds.yandex.net/i?id=0b4e976c8ec6e925501528cc73f191a73a5a06195f9e8522-3690429-images-thumbs&n=13",
    position: "Руководитель департамента менеджмента",
    level: 2,
    grade: "Senior",
    bossId: 444,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 440,
    first_name: "Александр",
    last_name: "Никитин",
    photo:
      "https://avatars.mds.yandex.net/i?id=31d8397e4cd53007b7d97c5a4f94b971b1640e7e-12475359-images-thumbs&n=13",
    position: "Руководитель департамента дизайна",
    level: 2,
    grade: "Senior",
    bossId: 444,
    departmentId: 202,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 427,
    first_name: "Лина",
    last_name: "Морозова",
    photo:
      "https://avatars.mds.yandex.net/i?id=d42769b3df38470eda8f6024d533e1e27d3def30-3948822-images-thumbs&n=13",
    position: "Руководитель проекта IT-компонент 3",
    level: 2,
    grade: "Senior",
    bossId: 444,
    employment_type: "Полная занятость",
    town: "Киров",
    timezone: "Europe/Kirov",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 426,
    first_name: "Петр",
    last_name: "Горонов",
    photo:
      "https://avatars.mds.yandex.net/i?id=028cec5e52cc5cd2e3b5414a458ccce543c31274f79c2307-5303121-images-thumbs&n=13",
    position: "Руководитель проекта IT-компонент 2",
    level: 2,
    grade: "Senior",
    bossId: 444,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 423,
    first_name: "Раджеш",
    last_name: "Кутраппали",
    photo:
      "https://avatars.mds.yandex.net/i?id=ed8d7a0e0489b84bf1c5e8b2e6a8c7e7a2ddee0c-13013698-images-thumbs&n=13",
    position: "Руководитель департамента девопс",
    level: 2,
    grade: "Senior",
    bossId: 444,
    departmentId: 226,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 422,
    first_name: "Екатерина",
    last_name: "Симонова",
    photo:
      "https://avatars.mds.yandex.net/i?id=7f3d8e0c3ef708de9d597676e2f2c594effb0b1b-4395455-images-thumbs&n=13",
    position: "Руководитель департамента HR",
    level: 2,
    grade: "Senior",
    bossId: 444,
    departmentId: 205,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 417,
    first_name: "Владимир",
    last_name: "Морозов",
    photo:
      "https://avatars.mds.yandex.net/i?id=26e36b0f6669fd89f1513e69345ac8af691fc00d-5221549-images-thumbs&n=13",
    position: "Руководитель департамента анализа",
    level: 2,
    grade: "Senior",
    bossId: 444,
    departmentId: 212,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 409,
    first_name: "Максим",
    last_name: "Некрасов",
    photo:
      "https://avatars.mds.yandex.net/i?id=0a336efe4a8ab4e724d7df13bab9050c6a228e48-4666409-images-thumbs&n=13",
    position: "Фронтенд-разработчик",
    level: 4,
    grade: "Middle",
    bossId: 405,
    componentId: 103,
    teamId: 305,
    departmentId: 203,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 404,
    first_name: "Сергей",
    last_name: "Петров",
    photo:
      "https://avatars.mds.yandex.net/i?id=ac46ff43f28b2f9c2ec0c4f19dc6dbb666e61abd-8316779-images-thumbs&n=13",
    position: "Бекенд-разработчик",
    level: 4,
    grade: "Junior",
    bossId: 402,
    componentId: 102,
    teamId: 304,
    departmentId: 203,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 443,
    first_name: "Георгий",
    last_name: "Гигашвилли",
    photo:
      "https://avatars.mds.yandex.net/i?id=e0c7f1f6f1d0683416627136712de8ea7948adb5b93e32a2-10247222-images-thumbs&n=13",
    position: "Девопс",
    level: 4,
    grade: "Middle",
    bossId: 424,
    componentId: 102,
    teamId: 312,
    departmentId: 226,
    employment_type: "Полная занятость",
    town: "Саратов",
    timezone: "Europe/Saratov",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 434,
    first_name: "Зинаида",
    last_name: "Полкова",
    photo:
      "https://avatars.mds.yandex.net/i?id=a0657c50136c761a0897e5cedf147632216f410e-8219723-images-thumbs&n=13",
    position: "HR",
    level: 4,
    grade: "Middle",
    bossId: 433,
    teamId: 311,
    departmentId: 205,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 415,
    first_name: "Анна",
    last_name: "Матвеева",
    photo:
      "https://avatars.mds.yandex.net/i?id=31dd62489ec480b25db74e3771851266315b4668-8497818-images-thumbs&n=13",
    position: "Веб-дизайнер",
    level: 4,
    grade: "Middle",
    bossId: 455,
    teamId: 303,
    departmentId: 202,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 437,
    first_name: "Алексей",
    last_name: "Соколов",
    photo:
      "https://avatars.mds.yandex.net/i?id=63e3d6a9a5baacfe946fdd366475fb1fe2b923ce74564497-12822923-images-thumbs&n=13",
    position: "Системный аналитик",
    level: 4,
    grade: "Junior",
    bossId: 416,
    componentId: 102,
    teamId: 307,
    departmentId: 212,
    employment_type: "Фриланс",
    town: "Калилинград",
    timezone: "Europe/Kaliningrad",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 435,
    first_name: "Ирина",
    last_name: "Торшина",
    photo:
      "https://avatars.mds.yandex.net/i?id=5dcf1dc8ff5744cb3177ef1769be71c734bf1888-10767497-images-thumbs&n=13",
    position: "Дизайнер",
    level: 4,
    grade: "Junior",
    bossId: 413,
    componentId: 102,
    teamId: 301,
    departmentId: 202,
    employment_type: "Фриланс",
    town: "Киров",
    timezone: "Europe/Kirov",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 449,
    first_name: "Арина",
    last_name: "Васильева",
    photo:
      "https://avatars.mds.yandex.net/i?id=b3d581ce7757bae19dd9a3be87b744f3-4230422-images-thumbs&n=13",
    position: "Системный аналитик",
    level: 4,
    grade: "Middle",
    bossId: 470,
    componentId: 104,
    teamId: 308,
    departmentId: 212,
    employment_type: "Фриланс",
    town: "Киров",
    timezone: "Europe/Kirov",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 421,
    first_name: "Алексей",
    last_name: "Макаров",
    photo:
      "https://avatars.mds.yandex.net/i?id=6e0a127b15dc9d0706e08951eb7d9228beb534d5954d6605-12788981-images-thumbs&n=13",
    position: "Маркетолог",
    level: 4,
    grade: "Middle",
    bossId: 420,
    teamId: 310,
    departmentId: 220,
    employment_type: "Фриланс",
    town: "Мадрид",
    timezone: "Europe/Madrid",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 420,
    first_name: "Петр",
    last_name: "Яковлев",
    photo:
      "https://avatars.mds.yandex.net/i?id=af4eaef026d0ecd984cefa2d2bd855915156af9e-10023438-images-thumbs&n=13",
    position: "Руководитель команды Маркетинг 1",
    level: 3,
    grade: "Team Lead",
    bossId: 482,
    teamId: 310,
    departmentId: 220,
    employment_type: "Полная занятость",
    town: "Волгоград",
    timezone: "Europe/Volgograd",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 419,
    first_name: "Николай",
    last_name: "Поляков",
    photo:
      "https://avatars.mds.yandex.net/i?id=70f8dc4ecaaffbc4aa2704c181156940101a7ef4-10471586-images-thumbs&n=13",
    position: "Менеджер",
    level: 4,
    grade: "Middle",
    bossId: 418,
    teamId: 309,
    departmentId: 215,
    employment_type: "Полная занятость",
    town: "Стамбул",
    timezone: "Europe/Istanbul",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 502,
    first_name: "Артем",
    last_name: "Кириллов",
    photo:
      "https://avatars.mds.yandex.net/i?id=fd7726bcd39fcdf279627364e9e3602ea2634a42-8209628-images-thumbs&n=13",
    position: "Девопс",
    level: 4,
    grade: "Junior",
    bossId: 424,
    componentId: 102,
    teamId: 312,
    departmentId: 226,
    employment_type: "Фриланс",
    town: "Стамбул",
    timezone: "Europe/Istanbul",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 442,
    first_name: "Лу",
    last_name: "Ван",
    photo:
      "https://avatars.mds.yandex.net/i?id=c371aecc78b2d5e7f79b54f1c82455d582fa87b5-5276035-images-thumbs&n=13",
    position: "Системный аналитик",
    level: 4,
    grade: "Junior",
    bossId: 416,
    componentId: 102,
    teamId: 307,
    departmentId: 212,
    employment_type: "Фриланс",
    town: "Амстердам",
    timezone: "Europe/Amsterdam",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 408,
    first_name: "Николай",
    last_name: "Сергеев",
    photo:
      "https://avatars.mds.yandex.net/i?id=209cffae22f00033009aa372a0d0dca1-5235569-images-thumbs&n=13",
    position: "Бекенд-разработчик",
    level: 4,
    grade: "Junior",
    bossId: 405,
    componentId: 103,
    teamId: 305,
    departmentId: 203,
    employment_type: "Фриланс",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 438,
    first_name: "Николай",
    last_name: "Орлов",
    photo:
      "https://avatars.mds.yandex.net/i?id=d2469e5a48834085bb16a9d6a25e3212876799e5-10464870-images-thumbs&n=13",
    position: "Системный аналитик",
    level: 4,
    grade: "Junior",
    bossId: 470,
    componentId: 104,
    teamId: 308,
    departmentId: 212,
    employment_type: "Фриланс",
    town: "Волгоград",
    timezone: "Europe/Volgograd",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 429,
    first_name: "Елена",
    last_name: "Плотникова",
    photo:
      "https://avatars.mds.yandex.net/i?id=3a7b2726d33941010535c1712e23015f0ffc3a3c-5539560-images-thumbs&n=13",
    position: "Девопс",
    level: 4,
    grade: "Middle",
    bossId: 431,
    componentId: 103,
    teamId: 313,
    departmentId: 226,
    employment_type: "Фриланс",
    town: "Будапешт",
    timezone: "Europe/Budapest",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 403,
    first_name: "Елена",
    last_name: "Кольцова",
    photo:
      "https://avatars.mds.yandex.net/i?id=273ef31ac0f859cf62ede53cb24c344400f9ad7355c4ce25-12728486-images-thumbs&n=13",
    position: "Фронтенд-разработчик",
    level: 4,
    grade: "Middle",
    bossId: 402,
    componentId: 102,
    teamId: 304,
    departmentId: 203,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 457,
    first_name: "Елена",
    last_name: "Плющева",
    photo:
      "https://avatars.mds.yandex.net/i?id=f93ab415299cb082d9295325304be7cc81780a94-9066051-images-thumbs&n=13",
    position: "Системный аналитик",
    level: 4,
    grade: "Junior",
    bossId: 470,
    componentId: 104,
    teamId: 308,
    departmentId: 212,
    employment_type: "Полная занятость",
    town: "Калининград",
    timezone: "Europe/Kaliningrad",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 464,
    first_name: "Никита",
    last_name: "Морозов",
    photo:
      "https://avatars.mds.yandex.net/i?id=6bb17cdecb107e97b1ce0c139dad9acf3c80e9fd-9212030-images-thumbs&n=13",
    position: "Руководитель проекта IT-компонент 1",
    level: 2,
    grade: "Senior",
    bossId: 444,
    departmentId: 212,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/Moscow",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 406,
    first_name: "Даниил",
    last_name: "Тихомиров",
    photo:
      "https://avatars.mds.yandex.net/i?id=23b66c94dd3e34a29865ce493f97f435af1d4cd6-10636899-images-thumbs&n=13",
    position: "Руководитель департамента девелопмента",
    level: 2,
    grade: "Senior",
    bossId: 444,
    employment_type: "Полная занятость",
    town: "Москва",
    timezone: "Europe/London",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 452,
    first_name: "Петр",
    last_name: "Янг",
    photo:
      "https://avatars.mds.yandex.net/i?id=e56311759bba2d37c323107ec1ebab6476eda47e-5679112-images-thumbs&n=13",
    position: "Бекенд-разработчик",
    level: 4,
    grade: "Junior",
    bossId: 410,
    componentId: 104,
    teamId: 306,
    departmentId: 203,
    employment_type: "Полная занятость",
    town: "Таллин",
    timezone: "Europe/Tallinn",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 432,
    first_name: "Петр",
    last_name: "Никитин",
    photo:
      "https://avatars.mds.yandex.net/i?id=e2e6f6f7f5b58c42317fd76b49cc8841af847233-5251249-images-thumbs&n=13",
    position: "Девопс",
    level: 4,
    grade: "Junior",
    bossId: 424,
    componentId: 102,
    teamId: 312,
    departmentId: 226,
    employment_type: "Полная занятость",
    town: "Варшава",
    timezone: "Europe/Warsaw",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
  {
    id: 459,
    first_name: "Чэнь",
    last_name: "Лин",
    photo:
      "https://avatars.mds.yandex.net/i?id=04ec2992f894b57b226c1d03843943aaf979c3ba-9196574-images-thumbs&n=13",
    position: "Фронтенд-разработчик",
    level: 4,
    grade: "Junior",
    bossId: 410,
    componentId: 104,
    teamId: 306,
    departmentId: 203,
    employment_type: "Фриланс",
    town: "Лондон",
    timezone: "Europe/London",
    contacts: {
      links: [
        "https://telegram.org",
        "https://myteam.mail.ru/webim",
        "https://www.atlassian.com/ru/software/jira",
      ],
    },
  },
];

////////////////////////////////////////////////////
export const projects = {
  components: [
    {
      id: 103,
      resources: [
        {
          id: 5,
          cost: 37000,
          progress: 35,
          teamId: 305,
        },
        {
          id: 6,
          cost: 43000,
          progress: 15,
          teamId: 313,
        },
      ],
      name: "Комонента 2",
      description: "",
      isActive: true,
      type: "web",
      status: "active",
      component_leadId: 426,
      teams: [305, 313],
    },
    {
      id: 104,
      resources: [
        {
          id: 7,
          cost: 37000,
          progress: 15,
          teamId: 307,
        },
        {
          id: 8,
          cost: 37000,
          progress: 45,
          teamId: 306,
        },
      ],
      name: "Комонента 3",
      description: "",
      isActive: true,
      type: "web",
      status: "active",
      component_leadId: 427,
      teams: [307, 306],
    },
    {
      id: 102,
      resources: [
        {
          id: 1,
          cost: 15000,
          progress: 25,
          teamId: 304,
        },
        {
          id: 2,
          cost: 35000,
          progress: 17,
          teamId: 307,
        },
        {
          id: 3,
          cost: 12000,
          progress: 37,
          teamId: 307,
        },
        {
          id: 4,
          cost: 16000,
          progress: 35,
          teamId: 312,
        },
      ],
      name: "Комонента 1",
      description: "",
      isActive: true,
      type: "web",
      status: "active",
      component_leadId: 464,
      teams: [307, 304, 301, 312],
    },
  ],
  departments: [
    {
      id: 203,
      department_leadId: 406,
      teamsId: [305, 304, 306],
      name: "Девелопмент",
    },
    {
      id: 202,
      department_leadId: 440,
      teamsId: [303, 301],
      name: "Дизайн",
    },
    {
      id: 215,
      department_leadId: 473,
      teamsId: [310],
      name: "Менеджмент",
    },
    {
      id: 212,
      department_leadId: 417,
      teamsId: [307, 308],
      name: "Анализ",
    },
    {
      id: 220,
      department_leadId: 482,
      teamsId: [310],
      name: "Маркетинг",
    },
    {
      id: 205,
      department_leadId: 422,
      teamsId: [311],
      name: "HR",
    },
    {
      id: 226,
      department_leadId: 423,
      teamsId: [313, 312],
      name: "Девопсы",
    },
  ],
  teams: [
    {
      id: 305,
      name: "Команда Девелопмент 2",
      team_type: "STAFF",
      performance: "Опытная слаженная команда разработчиков.",
      description:
        "Команда имеет обширный опыт решения сложных технических задач.",
      team_leadId: 405,
      componentIds: 104,
      departmentId: 203,
      usersId: [405, 409, 408],
    },
    {
      id: 313,
      name: "Команда Девопсы 2",
      team_type: "STAFF",
      performance: "Опытная слаженная команда разработчиков.",
      description:
        "Команда имеет обширный опыт решения сложных технических задач.",
      team_leadId: null,
      componentIds: null,
      departmentId: 226,
      usersId: [431, 429],
    },
    {
      id: 307,
      name: "Команда Анализ 1",
      team_type: "STAFF",
      performance: "Опытная слаженная команда разработчиков.",
      description:
        "Команда имеет обширный опыт решения сложных технических задач.",
      team_leadId: 416,
      componentIds: 102,
      departmentId: 212,
      usersId: [416, 437],
    },
    {
      id: 303,
      name: "Команда Дизайн 2",
      team_type: "STAFF",
      performance: "Опытная слаженная команда разработчиков.",
      description:
        "Команда имеет обширный опыт решения сложных технических задач.",
      team_leadId: 455,
      componentIds: null,
      departmentId: 202,
      usersId: [455, 415],
    },
    {
      id: 304,
      name: "Команда Девелопмент 1",
      team_type: "STAFF",
      performance: "Опытная слаженная команда разработчиков.",
      description:
        "Команда имеет обширный опыт решения сложных технических задач.",
      team_leadId: 402,
      componentIds: 102,
      departmentId: 203,
      usersId: [402, 404, 403],
    },
    {
      id: 309,
      name: "Команда Менеджмент 1",
      team_type: "OUTSOURCE",
      performance: "Опытная слаженная команда разработчиков.",
      description:
        "Команда имеет обширный опыт решения сложных технических задач.",
      team_leadId: 418,
      componentIds: null,
      departmentId: 215,
      usersId: [418, 419],
    },
    {
      id: 311,
      name: "Команда HR 1",
      team_type: "STAFF",
      performance: "Опытная слаженная команда разработчиков.",
      description:
        "Команда имеет обширный опыт решения сложных технических задач.",
      team_leadId: 433,
      componentIds: null,
      departmentId: 205,
      usersId: [433, 434],
    },
    {
      id: 301,
      name: "Команда Дизайн 1",
      team_type: "STAFF",
      performance: "Опытная слаженная команда разработчиков.",
      description:
        "Команда имеет обширный опыт решения сложных технических задач.",
      team_leadId: 413,
      componentIds: 102,
      departmentId: 202,
      usersId: [413, 414, 435],
    },
    {
      id: 308,
      name: "Команда Анализ 2",
      team_type: "STAFF",
      performance: "Опытная слаженная команда разработчиков.",
      description:
        "Команда имеет обширный опыт решения сложных технических задач.",
      team_leadId: 470,
      componentIds: 104,
      departmentId: 212,
      usersId: [470, 449, 438, 457],
    },
    {
      id: 312,
      name: "Команда Девопсы 1",
      team_type: "OUTSOURCE",
      performance: "Опытная слаженная команда разработчиков.",
      description:
        "Команда имеет обширный опыт решения сложных технических задач.",
      team_leadId: 424,
      componentIds: 102,
      departmentId: 226,
      usersId: [424, 443, 502, 432],
    },
    {
      id: 306,
      name: "Команда Девелопмент 3",
      team_type: "OUTSOURCE",
      performance: "Опытная слаженная команда разработчиков.",
      description:
        "Команда имеет обширный опыт решения сложных технических задач.",
      team_leadId: 410,
      componentIds: 104,
      departmentId: 203,
      usersId: [411, 410, 412, 452, 459],
    },
    {
      id: 310,
      name: "Команда Маркетинг 1",
      team_type: "OUTSOURCE",
      performance: "Опытная слаженная команда разработчиков.",
      description:
        "Команда имеет обширный опыт решения сложных технических задач.",
      team_leadId: 420,
      componentIds: null,
      departmentId: 220,
      usersId: [421, 420],
    },
  ],
};

////////////////////////////////////////////////////
export const user = {
  id: 402,
  first_name: "Иван",
  last_name: "Петров",
  photo: "https://kahoot.com/files/2018/02/padraic_avatar.png",
  position: "Руководитель команды Девелопмент 1",
  level: 3,
  grade: "Team Lead",
  bossId: 406,
  teamId: 304,
  componentId: 102,
  departmentId: 203,
  employment_type: "Полная занятость",
  timezone: "Europe/Moscow",
  town: "Москва",
  foreign_languages: ["Английский"],
  programs: ["Python"],
  skills: ["Бекенд-разработка"],
  contacts: {
    links: [
      "https://telegram.org",
      "https://myteam.mail.ru/webim",
      "https://www.atlassian.com/ru/software/jira",
    ],
    emails: ["copr@mail.com", "personal@mail.com"],
    phones: ["+7(923)4567890", "+7(942)4646484"],
  },
};
